language: python
python: 
  - "2.7"
before_install:
  - cd flaskplayground
install: 
  - ./virtualize.sh
script:
  - venv/bin/python -m unittest discover
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a2899ec6cc49151dbb9e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
