from collections import OrderedDict
column_names_and_order = {
    "child.csv": OrderedDict([
        ("fss_child_id", "ID"),
        ("fss_child_child_english_name", "English Name"),
        ("fss_child_child_chinese_name", "Chinese Name"),
        ("fss_child_child_pinyin_name", "Pinyin Name"),
        ("fss_child_nickname", "Nickname"),
        ("fss_child_gender", "Gender"),
        ("fss_child_birth_date", "Birth Date"),
        ("fss_child_referred_by", "Reffered By"),
        ("fss_child_status", "Status"),
        ("fss_child_primary_diagnosis", "Primary Diagnosis"),
        ("fss_child_primary_diagnosis_note", "Diagnosis Notes"),
        ("fss_child_secondary_diagnosis", "Secondary Diagnosis"),
        ("fss_child_secondary_diagnosis_note", "Secondary Diagnosis Notes"),
        ("fss_child_further_diagnosis", "Further Diagnosis"),
        ("fss_child_reason_for_referral", "Reason For Referral"),
        ("fss_child_birth_history", "Birth History"),
        ("fss_child_medical_history", "Medical History"),
        ("fss_child_family_dynamics", "Family Dynamics"),
        ("fss_child_other_family_members", "Other Family Members"),
    ]),
    "family.csv": OrderedDict([
        ("fss_family_member_id", "ID"),
        ("fss_family_member_child_id", "Child ID"),
        ("fss_child_status", "Child Status"),
        ("fss_child_child_english_name", "Child English Name"),
        ("fss_child_child_chinese_name", "Child Chinese Name"),
        ("fss_child_child_pinyin_name", "Child Pinyin Name"),
        ("fss_family_member_relationship", "Relationship"),
        ("fss_family_member_family_member_name", "Name"),
        ("fss_family_member_family_member_phone", "Phone"),
        ("fss_family_member_family_member_email", "Email"),
        ("fss_family_member_family_member_wechat", "WeChat"),
        ("fss_family_member_family_member_address", "Address"),
        ("fss_family_member_family_member_notes", "Notes"),
        ("fss_family_member_family_member_is_primary", "Primary Caregiver"),
    ]),
    "pathway.csv": OrderedDict([
        ("fss_projected_pathway_id", "ID"),
        ("fss_projected_pathway_child_id", "Child ID"),
        ("fss_child_status", "Child Status"),
        ("fss_child_child_english_name", "Child English Name"),
        ("fss_child_child_chinese_name", "Child Chinese Name"),
        ("fss_child_child_pinyin_name", "Child Pinyin Name"),
        ("fss_projected_pathway_pathway_step_number", "Step Number"),
        ("fss_projected_pathway_pathway_short_description", "Short Description"),
        ("fss_projected_pathway_pathway_details", "Details"),
        ("fss_projected_pathway_pathway_completion_date", "Completion Date"),
    ]),
    "interaction.csv": OrderedDict([
        ("fss_interaction_id", "ID"),
        ("fss_interaction_child_id", "Child ID"),
        ("fss_child_status", "Child Status"),
        ("fss_child_child_english_name", "Child English Name"),
        ("fss_child_child_chinese_name", "Child Chinese Name"),
        ("fss_child_child_pinyin_name", "Child Pinyin Name"),
        ("fss_interaction_interaction_date", "Date"),
        ("fss_interaction_interaction_type", "Type"),
        ("fss_interaction_interaction_coordinator", "Coordinator"),
        ("fss_interaction_people_present", "People Present"),
        ("fss_interaction_is_initial_interaction", "Initial Interaction"),
        ("fss_interaction_current_concerns", "Current Concerns"),
        ("fss_interaction_dev_history", "Developmental History"),
        ("fss_interaction_dev_since_last_visit", "Developments Since Last Visit"),
        ("fss_interaction_follow_up", "Follow Up"),
        ("fss_interaction_interaction_notes", "Interaction Notes"),

        ("fss_interaction_milk_feeding", "Milk Feeding"),
        ("fss_interaction_solid_feeding", "Solid Feeding"),
        ("fss_interaction_self_feeding", "Self Feeding"),
        ("fss_interaction_texture_preferences", "Texture Preferences"),
        ("fss_interaction_feeding_recommendations", "Feeding Recommendations"),
        ("fss_interaction_developmental_notes", "Developmental Notes"),
        ("fss_interaction_developmental_recommendations", "Developmental Recommendations"),
        ("fss_interaction_ot_notes", "OT Notes"),
        ("fss_interaction_ot_recommendations", "OT Recommendations"),
        ("fss_interaction_sensory_notes", "Sensory Notes"),
        ("fss_interaction_sensory_recommendations", "Sensory Recommendations"),
        ("fss_interaction_speech_notes", "Speech Notes"),
        ("fss_interaction_speech_recommendations", "Speech Recommendations"),
        ("fss_interaction_head_control", "Head Control"),
        ("fss_interaction_rolling", "Rolling"),
        ("fss_interaction_sitting", "Sitting"),
        ("fss_interaction_standing", "Standing"),
        ("fss_interaction_walking", "Walking"),
        ("fss_interaction_physical_recommendations", "Physical Recommendations"),
        ("fss_interaction_gross_motor_notes", "Gross Motor Notes"),
        ("fss_interaction_gross_motor_recommendations", "Gross Motor Recommendations"),
        ("fss_interaction_fine_motor_notes", "Fine Motor Notes"),
        ("fss_interaction_fine_motor_recommendations", "Fine Motor Recommendations"),
        ("fss_interaction_weakness_notes", "Weakness Notes"),
        ("fss_interaction_weakness_recommendations", "Weakness Recommendations"),
    ]),
    "fss.csv": OrderedDict([
        ("fss_child_id", "ID"),
        ("fss_child_child_english_name", "English Name"),
        ("fss_child_child_chinese_name", "Chinese Name"),
        ("fss_child_child_pinyin_name", "Pinyin Name"),
        ("fss_child_nickname", "Nickname"),
        ("fss_child_gender", "Gender"),
        ("fss_child_birth_date", "Birth Date"),
        ("fss_child_referred_by", "Reffered By"),
        ("fss_child_status", "Status"),
        ("fss_child_primary_diagnosis", "Primary Diagnosis"),
        ("fss_child_primary_diagnosis_note", "Diagnosis Notes"),
        ("fss_child_secondary_diagnosis", "Secondary Diagnosis"),
        ("fss_child_secondary_diagnosis_note", "Secondary Diagnosis Notes"),
        ("fss_child_further_diagnosis", "Further Diagnosis"),
        ("fss_child_reason_for_referral", "Reason For Referral"),
        ("fss_child_birth_history", "Birth History"),
        ("fss_child_medical_history", "Medical History"),
        ("fss_child_family_dynamics", "Family Dynamics"),
        ("fss_child_other_family_members", "Other Family Members"),

        ("fss_family_member_id", "ID"),
        ("fss_family_member_child_id", "Child ID"),
        ("fss_family_member_relationship", "Relationship"),
        ("fss_family_member_family_member_name", "Name"),
        ("fss_family_member_family_member_phone", "Phone"),
        ("fss_family_member_family_member_email", "Email"),
        ("fss_family_member_family_member_wechat", "WeChat"),
        ("fss_family_member_family_member_address", "Address"),
        ("fss_family_member_family_member_notes", "Notes"),
        ("fss_family_member_family_member_is_primary", "Primary Caregiver"),

        ("fss_projected_pathway_id", "ID"),
        ("fss_projected_pathway_child_id", "Child ID"),
        ("fss_projected_pathway_pathway_step_number", "Step Number"),
        ("fss_projected_pathway_pathway_short_description", "Short Description"),
        ("fss_projected_pathway_pathway_details", "Details"),
        ("fss_projected_pathway_pathway_completion_date", "Completion Date"),

        ("fss_interaction_id", "ID"),
        ("fss_interaction_child_id", "Child ID"),
        ("fss_interaction_interaction_date", "Date"),
        ("fss_interaction_interaction_type", "Type"),
        ("fss_interaction_interaction_coordinator", "Coordinator"),
        ("fss_interaction_people_present", "People Present"),
        ("fss_interaction_is_initial_interaction", "Initial Interaction"),
        ("fss_interaction_current_concerns", "Current Concerns"),
        ("fss_interaction_dev_history", "Developmental History"),
        ("fss_interaction_dev_since_last_visit", "Developments Since Last Visit"),
        ("fss_interaction_follow_up", "Follow Up"),
        ("fss_interaction_interaction_notes", "Interaction Notes"),

        ("fss_interaction_milk_feeding", "Milk Feeding"),
        ("fss_interaction_solid_feeding", "Solid Feeding"),
        ("fss_interaction_self_feeding", "Self Feeding"),
        ("fss_interaction_texture_preferences", "Texture Preferences"),
        ("fss_interaction_feeding_recommendations", "Feeding Recommendations"),
        ("fss_interaction_developmental_notes", "Developmental Notes"),
        ("fss_interaction_developmental_recommendations", "Developmental Recommendations"),
        ("fss_interaction_ot_notes", "OT Notes"),
        ("fss_interaction_ot_recommendations", "OT Recommendations"),
        ("fss_interaction_sensory_notes", "Sensory Notes"),
        ("fss_interaction_sensory_recommendations", "Sensory Recommendations"),
        ("fss_interaction_speech_notes", "Speech Notes"),
        ("fss_interaction_speech_recommendations", "Speech Recommendations"),
        ("fss_interaction_head_control", "Head Control"),
        ("fss_interaction_rolling", "Rolling"),
        ("fss_interaction_sitting", "Sitting"),
        ("fss_interaction_standing", "Standing"),
        ("fss_interaction_walking", "Walking"),
        ("fss_interaction_physical_recommendations", "Physical Recommendations"),
        ("fss_interaction_gross_motor_notes", "Gross Motor Notes"),
        ("fss_interaction_gross_motor_recommendations", "Gross Motor Recommendations"),
        ("fss_interaction_fine_motor_notes", "Fine Motor Notes"),
        ("fss_interaction_fine_motor_recommendations", "Fine Motor Recommendations"),
        ("fss_interaction_weakness_notes", "Weakness Notes"),
        ("fss_interaction_weakness_recommendations", "Weakness Recommendations"),
    ]),
}
