from collections import OrderedDict
column_names_and_order = OrderedDict([
    ("fss_child_id", "ID"),
    ("fss_child_child_english_name", "English Name"),
    ("fss_child_child_chinese_name", "Chinese Name"),
    ("fss_child_child_pinyin_name", "Pinyin Name"),
    ("fss_child_nickname", "Nickname"),
    ("fss_child_gender", "Gender"),
    ("fss_child_birth_date", "Birth Date"),
    ("fss_child_referred_by", "Reffered By"),
    ("fss_child_status", "Status"),
    ("fss_child_primary_diagnosis", "Primary Diagnosis"),
    ("fss_child_primary_diagnosis_note", "Diagnosis Notes"),
    ("fss_child_secondary_diagnosis", "Secondary Diagnosis"),
    ("fss_child_secondary_diagnosis_note", "Secondary Diagnosis Notes"),
    ("fss_child_further_diagnosis", "Further Diagnosis"),
    ("fss_child_reason_for_referral", "Reason For Referral"),
    ("fss_child_birth_history", "Birth History"),
    ("fss_child_medical_history", "Medical History"),
    ("fss_child_family_dynamics", "Family Dynamics"),
    ("fss_child_other_family_members", "Other Family Members"),

    ("fss_family_member_child_id", "ID"),
    ("fss_family_member_relationship", "Relationship"),
    ("fss_family_member_family_member_name", "Name"),
    ("fss_family_member_family_member_phone", "Phone"),
    ("fss_family_member_family_member_email", "Email"),
    ("fss_family_member_family_member_wechat", "WeChat"),
    ("fss_family_member_family_member_address", "Address"),
    ("fss_family_member_family_member_notes", "Notes"),
    ("fss_family_member_family_member_is_primary", "Primary Caregiver"),
])
